{
    "name": "BoQ",
    "summary": "Bill of Quantity ",
    "description": "Module for managing Bill of Quantity",
    "author": "Your Company",
    "website": "https://yourcompany.com",
    "version": "1.0.0",
    "category": "Customizations",
    "depends": ["base", "product", "sale", "uom"],
    "data": [
        "views/boq_root_views.xml",
        "views/work_unit_views.xml",
        "views/work_unit_others_views.xml",
        "views/line/material_line_views.xml",
        "views/line/service_line_views.xml",
        "views/variant/material_variant_views.xml",
        "views/masterdata/material_master_views.xml",
        "views/menu_boq_views.xml",
    ],
    "license": "AGPL-3",
    "installable": True,
    "application": True,
}