{
    "name": "BoQ",
    "summary": "Bill of Quantity ",
    "description": "Module for managing Bill of Quantity",
    "author": "Your Company",
    "website": "https://yourcompany.com",
    "version": "1.0.0",
    "category": "Customizations",
    "depends": ["base", "product"],
    "data": [
        "views/boq_root_views.xml",
        "views/work_unit_views.xml",
        "views/work_unit_material_views.xml",
        "views/work_unit_service_views.xml",
        "views/work_unit_others_views.xml",
        "views/menu_boq_views.xml",
    ],
    "license": "AGPL-3",
    "installable": True,
    "application": True,
}